name: CI

on:
  pull_request: {}
  push:
    branches:
    - master
    - release/*

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name : Checkout repository
      # https://github.com/actions/checkout/releases/tag/v4.1.1
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Install Go
      # https://github.com/actions/setup-go/releases/tag/v5.0.0
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version-file: 'go.mod'
    - name: Install mockgen
      run: go install go.uber.org/mock/mockgen@v0.4.0
    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64 # v6.0.1
      with:
        version: v1.59.0
    - name: Install env-test
      run: go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
    - name: Build
      run: make build-bin
    - name: Test
      run: make test
    - name: Validate
      run: make validate
